### ISSUE TITLE
Gestion de l'authentification avec l'API

### ISSUE THREAD

**Issue by hugoseri** [PierreCIT/MyComifClient#10]

**Comment by jcchevalier** [comment]
As said in a previous issue, to authenticate you must use a POST request at the URL `https://comif.fr/api/users/login`, with a specific JSON as a body: `{"client_id":1, "client_secret":"secret", "grant_type":"password", "username":"USERNAME", "password":"PASSWORD"}`.
The server then returns another JSON containing the Bearer token needed to authenticate a legitimate each request made by the user. To do so, you must add a new parameter to the header of each request: `Authorization: Bearer {access_token}`. If the token is validated server-side, the server will send a response. Otherwise a 401 error will be thrown.

**Comment by jcchevalier** [comment]
Part of the authentification service has been implemented with the #17 pull request. The response is correctly handled and it stocks the token inside the local database of the smartphone. Bearer are also automatically added to each header of the `GET` requests, identifying and authorizing each request made.
